config/routes.rb
Rails.application.routes.draw do
 
  
  
  root 'pages#Index'

  resources :vets
  resources :pets
  devise_for :users, :controllers => { registrations: 'registrations' }
  devise_for :offices, :controllers => {:registrations => "office/registrations"}
  

  get '/home' => 'pages#Home'

  get '/user/:id' => 'pages#Profile'

  get '/explore' => 'pages#Explore'

  get '/office/:id' => 'pages#Office'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/office.rb
class Office < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :vets
end

app/models/pet.rb
class Pet < ApplicationRecord
	has_attached_file :image, styles: { medium: "50x50>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
	belongs_to :user 
	validates :user_id, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pets
end

app/models/vet.rb
class Vet < ApplicationRecord
has_attached_file :image, styles: { medium: "50x50>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  belongs_to :office
  validates :office_id, presence: true 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception


  
end

app/controllers/office/registrations_controller.rb
class Office::RegistrationsController < Devise::RegistrationsController
	private 

	   def sign_up_params
    params.require(:office).permit(:first_name, :last_name, :address, :apt_num, :city, :state, :zip_code, :email, :password, 
    	:password_confirmation, :business_category, :business_name, :dob, :card_name, :card_number, :exp_month, :exp_year,
    	 :cvv, :billing_address,:billing_apt_num, :billing_state, :billing_city, :billing_zip_code, :routing_number, :account_number )
  end

  def account_update_params
    params.require(:office).permit(:first_name, :last_name, :address, :apt_num, :city, :state, :zip_code, :email, :password, 
    	:password_confirmation, :current_password, :business_category, :business_name, :dob, :card_name, :card_number, :exp_month, :exp_year,
    	 :cvv, :billing_address,:billing_apt_num, :billing_state, :billing_city, :billing_zip_code, :routing_number, :account_number )
  end


end
       

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def Index
  end

  def Home
  	@vets = Vet.all 
  end

  def Profile
  	if (User.find_by_first_name(params[:id]))
  		@first_name = params[:id]
  	else 
  		redirect_to root_path, :notice => "user not found"
  	end 

  	@pets = Pet.all.where("user_id = ? ", User.find_by_first_name(params[:id]).id)
  	@newPet = Pet.new
  end

  def Explore
  	@vets = Vet.all 
  end

  def Office
    if (Office.find_by_business_name(params[:id]))
      @business_name = params[:id]
    else 
      redirect_to root_path, :notice => "office not found"
    end 
  @vets = Vet.all.where("office_id = ? ", Office.find_by_business_name(params[:id]).id)
    @newVet = Vet.new
  end

  def Vet 
  end 




end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

	def new 
		@pet = Pet.new 
	end 

	def create 
		@pet = Pet.new(pet_params)
		@pet.user_id = current_user.id
		respond_to do |f| 
			if (@pet.save)
				f.html {redirect_to "" , notice: "Pet Added to Your Profile"}
			else 
				f.html {redirect_to "" , notice: "Pet Cannot Be Saved "}
			end 
		end 
	end 


	private 
	def pet_params 
		params.require(:pet).permit(:user_id, :pet_name, :image, :pet_age,  :about, :tpe, :weight, :height, :size, :breed, :sex, :spay, :allergies, :medications, :vaccine )

		end 
	end 

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :address, :apt_num, :city, :state, :zip_code, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :address, :apt_num, :city, :state, :zip_code, :email, :password, :password_confirmation, :current_password)
  end


end
          

app/controllers/vets_controller.rb
class VetsController < ApplicationController

	def new 
		@vet = Vet.new 
	end 

	def create 
		@vet = Vet.new(vet_params)
		@vet.office_id = current_office.id
		respond_to do |f| 
			if (@vet.save)
				f.html {redirect_to "" , notice: "Vet Added to Your Office"}
			else 
				f.html {redirect_to "" , notice: "Vet Cannot Be Saved "}
			end 
		end 
	end 


			private 

			def vet_params
				params.require(:vet).permit(:office_id, :image, :vet_name, :about, :website, :facebook, :twitter, :linkedin)
		end 
	end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_nav.html.erb
<% if user_signed_in?%>
<%= render '/layouts/nav_user' %>
<%elsif office_signed_in?%>
<%=render 'layouts/nav_office'%>
<%else%>
<%= render '/layouts/nav_guest' %>
<%end%>

app/views/layouts/_nav_guest.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">PetCreds</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">My Care Center</a></li>
        
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Navigation <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to('list your business', new_office_registration_path) %> </li>
           <li><%= link_to('Sign up', new_user_registration_path) %> </li>
            <li><%= link_to('login', new_user_session_path) %> </li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_office.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"> PetCreds</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">My Care Center</a></li>
        
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_office.business_name%> <span class="caret"></span></a>
          <ul class="dropdown-menu">
           <li><a href="/office/<%= current_office.business_name%>">Profile</a></li>
             <li><%= link_to('Settings', edit_office_registration_path) %> </li>
            <li><%= link_to('log out', destroy_office_session_path, :method => :delete) %> </li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_nav_user.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">PetCreds</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">My Care Center</a></li>
        
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name%> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/user/<%= current_user.first_name%>">Profile</a></li>
             <li><%= link_to('Settings', edit_user_registration_path) %> </li>
            <li><%= link_to('log out', destroy_user_session_path, :method => :delete) %> </li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>

          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sendbird</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>
    <div class="container">
      <span class="notice"><%= notice %></span>
       <span class="alert"><%= alert %></span>
    <%= yield %>
    </div>
  </body>
</html>

app/views/offices/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/pages/Explore.html.erb
<h1>Pages#Explore</h1>
<p>Find me in app/views/pages/Explore.html.erb</p>

app/views/pages/Home.html.erb
<!--THe Body -->


<div class="row">
	<div class="col-xs-3">
		<div class="panel panel=default">
			<div class="panel-body">
			<p>stats</p>
			</div>
		</div>
	</div>
	
<div class="row">
	<div class="col-xs-6">
	<% for @v in @vets %>
		<div class="panel panel=default">
			<div class="panel-body">
			<p><%= image_tag @v.image.url(:thumb) %></p>
			<p> Vet Name:  <%= @v.vet_name %> | About:  <%= @v.about %> | Website:  <%= @v.website %>  </p>
			</div>
		</div>
		<%end%>
	</div>
<div class="row">
	<div class="col-xs-3">
		<div class="panel panel=default">
			<div class="panel-body">
			<p>about</p>
			</div>
		</div>
	</div>
<!-- second row  -->
<div class="row">
	<div class="col-xs-3 col-xs-offset-9">
		<div class="panel panel=default">
			<div class="panel-body">
			<p>trends</p>
			</div>
		</div>
	</div>
  </div>
 	</div>
		</div>
			</div>

app/views/pages/Index.html.erb
<h1>Pages#Index</h1>
<p>Find me in app/views/pages/Index.html.erb</p>
</br> 
	</br> 
		</br> 
	</br> 
</br> 
<li><%= link_to('Office Login', new_office_session_path) %> </li>

app/views/pages/Office.html.erb
<div class="jumbotron">
<h1><%= current_office.business_name %> </h1> 
<h2><%= current_office.business_category %></h2>

  <p><%= current_office.address%> <%= current_office.city%> <%= current_office.state%> <%= current_office.zip_code%></p>
  <p><%= current_office.email%> </p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn less</a></p>
</div>

<!--THe Body -->


<div class="row">
	<div class="col-xs-3">
	<%=render '/components/vet_form'%>
		<div class="panel panel=default">
			<div class="panel-body">
			<p>stats</p>
			</div>
		</div>
	</div>
	
<div class="row">
	<div class="col-xs-6">
	<% for @v in @vets %>
		<div class="panel panel=default">
			<div class="panel-body">

			<p><%= image_tag @v.image.url(:thumb) %></p>	
			<p> Vet Name:  <%= @v.vet_name %>  </p>
			|<p> About: <%= @v.about %>  </p>
          <p>Website <%= @v.website %> | Website <%= @v.facebook %> | Website <%= @v.twitter %> | Website <%= @v.linkedin%></p>
			</div>
		</div>
		<%end%>
	</div>
<div class="row">
	<div class="col-xs-3">
		<div class="panel panel=default">
			<div class="panel-body">
			<p>about</p>
			</div>
		</div>
	</div>
<!-- second row  -->
<div class="row">
	<div class="col-xs-3 col-xs-offset-9">
		<div class="panel panel=default">
			<div class="panel-body">
			<p>trends</p>
			</div>
		</div>
	</div>
  </div>
 	</div>
		</div>
			</div>

app/views/pages/Profile.html.erb
<div class="jumbotron">
  <h1><%= current_user.first_name %>  <%= current_user.last_name %> </h1> 
  <h2></h2>

  <p>Consultant Feed at your service</p>
  <p>profile page</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

<!--THe Body -->


<div class="row">
	<div class="col-xs-3">
	<%=render '/components/pet_form'%>
		<div class="panel panel=default">
			<div class="panel-body">
			<p>stats</p>
			</div>
		</div>
	</div>
	
<div class="row">
	<div class="col-xs-6">
	<% for @p in @pets %>
		<div class="panel panel=default">
			<div class="panel-body">

			 <p><%= image_tag @p.image.url(:thumb) %></p>	
			<p> Pet Name:  <%= @p.pet_name %> | Age:  <%= @p.pet_age %> | Type:  <%= @p.tpe %>  </p>
			<p> About:  <%= @p.about %> </p> 
			<p> Weight: <%= @p.weight %>  |Height: <%= @p.height %> | Size: <%= @p.size %> </p>
			<p> Breed: <%= @p.breed %>  |Sex:  <%= @p.sex %> |Spayed: <%= @p.spay %> </p>
			<p>Allergies:  <%= @p.allergies %>  | Medications: <%= @p.medications %> | Vaccines: <%= @p.vaccine %> </p>

			</div>
		</div>
		<%end%>
	</div>
<div class="row">
	<div class="col-xs-3">
		<div class="panel panel=default">
			<div class="panel-body">
			<p>about</p>
			</div>
		</div>
	</div>
<!-- second row  -->
<div class="row">
	<div class="col-xs-3 col-xs-offset-9">
		<div class="panel panel=default">
			<div class="panel-body">
			<p>trends</p>
			</div>
		</div>
	</div>
  </div>
 	</div>
		</div>
			</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>